### ISSUE TITLE
Adding Soul Mixer To Game

### ISSUE THREAD

**Issue by mtogi** [AcidCaos/socialemperors#27]
Soul mixer was such an important part of the game. It should be added if possible.

**Comment by Nerroth** [comment]
At the moment there are no plans to add the Soul Mixer, work needs to be done on the codebase for the server first to be able to save your progress properly, there are lots of things that need to be worked on before we start thinking about Soul Mixer.

And on top of that, required data related to the Soul Mixer is missing from the config so we would have to add that in manually in order for it to be functional. This is a time consuming process due to the amount of tweaks we would have to do in order to make the Soul Mixer as similar as possible to how it used to be.
